xr_gather_items.evaluator_gather_items.evaluate = function(self)
	if self.a.gather_items_enabled ~= true then
		return false
	end
	--/ SGM in
	if sgm_functions.ReadGatherDetection(self.object:section()) == false then
		return false
	end
	if sgm_g.exists(sgm_g.get_object_squad_name(self.object)) and sgm_functions.ReadAssaultSquad(get_object_squad(self.object).settings_id) then
		return false
	end
	--/ SGM out

	return self.object:is_there_items_to_pickup()
end
